version: "3"
services:
  db:
    image: postgres:alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports: 
      - "6379:6379"
      
volumes:
  db-data:
