version: "3"
services:
  db:
    image: postgres:alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
